#!/bin/bash

cp /etc/exim/exim4.conf /var/lib/exim4/config.autogenerated
chmod 600 /var/lib/exim4/config.autogenerated
chown root:root /var/lib/exim4/config.autogenerated

/usr/sbin/exim -bd -v -q30m
